/** Every rule ID in one place. IDs are stable: never reuse or renumber one. */
export const RULE_IDS = {
  HTTP_CSP_MISSING: 'HTTP-001',
  HTTP_HSTS_MISSING: 'HTTP-002',
  HTTP_CONTENT_TYPE_OPTIONS_MISSING: 'HTTP-003',
  HTTP_FRAME_PROTECTION_MISSING: 'HTTP-004',
  HTTP_REFERRER_POLICY_MISSING: 'HTTP-005',
  HTTP_SERVER_VERSION_DISCLOSED: 'HTTP-006',
  HTTP_POWERED_BY_DISCLOSED: 'HTTP-007',
  HTTP_NO_HTTPS_REDIRECT: 'HTTP-008',

  COOKIE_SECURE_MISSING: 'COOKIE-001',
  COOKIE_HTTPONLY_MISSING: 'COOKIE-002',
  COOKIE_SAMESITE_MISSING: 'COOKIE-003',

  TLS_CERT_EXPIRED: 'TLS-001',
  TLS_CERT_EXPIRING: 'TLS-002',
  TLS_CERT_SELF_SIGNED: 'TLS-003',
  TLS_CERT_HOSTNAME_MISMATCH: 'TLS-004',

  DNS_SPF_MISSING: 'DNS-001',
  DNS_DMARC_MISSING: 'DNS-002',
  DNS_CAA_MISSING: 'DNS-003',
  DNS_SPF_PERMISSIVE: 'DNS-004',
  DNS_DMARC_MONITORING_ONLY: 'DNS-005',

  TCP_PORT_OPEN: 'TCP-001',
} as const;

export type RuleId = (typeof RULE_IDS)[keyof typeof RULE_IDS];
